// HandWrite AI — UI layer on top of engine.js
(function() {
  'use strict';

  var textInput = document.getElementById('text-input');
  var charCount = document.getElementById('char-count');
  var drawButton = document.getElementById('draw-button');
  var actionsSection = document.getElementById('actions-section');
  var saveBtn = document.getElementById('save-button');
  var shareBtn = document.getElementById('share-btn');
  var canvasContainer = document.getElementById('canvas-container');
  var header = document.getElementById('app-header');

  // Character counter
  textInput.addEventListener('input', function() {
    charCount.textContent = textInput.value.length + '/50';
  });

  // Show actions after writing
  document.addEventListener('writing-complete', function() {
    actionsSection.style.display = '';
  });

  // Model ready — auto-generate welcome
  document.addEventListener('model-ready', function() {
    // Auto-generate "Welcome" after a short delay
    setTimeout(function() {
      if (textInput.value === '') {
        textInput.value = 'Welcome';
        charCount.textContent = '7/50';
        drawButton.click();
      }
    }, 300);
  });

  // Paper background switching
  var paperBtns = document.querySelectorAll('.paper-btn');
  paperBtns.forEach(function(btn) {
    btn.addEventListener('click', function() {
      paperBtns.forEach(function(b) { b.classList.remove('active'); });
      btn.classList.add('active');
      var paper = btn.getAttribute('data-paper');
      canvasContainer.className = 'paper-' + paper;
    });
  });

  // Share button
  shareBtn.addEventListener('click', function() {
    if (navigator.share) {
      var svgEl = document.getElementById('canvas');
      var data = new XMLSerializer().serializeToString(svgEl);
      var blob = new Blob([data], {type: 'image/svg+xml'});
      var file = new File([blob], 'handwriting.svg', {type: 'image/svg+xml'});
      navigator.share({
        title: 'HandWrite AI',
        text: 'Handwriting generated by HandWrite AI',
        files: [file]
      }).catch(function() {});
    }
  });

  // Header shrink on scroll (mobile)
  var lastScroll = 0;
  window.addEventListener('scroll', function() {
    var st = window.pageYOffset || document.documentElement.scrollTop;
    if (st > 60) {
      header.classList.add('shrink');
    } else {
      header.classList.remove('shrink');
    }
    lastScroll = st;
  }, {passive: true});

  // Service worker
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('sw.js').catch(function() {});
  }

  // PWA install prompt
  var deferredPrompt = null;
  window.addEventListener('beforeinstallprompt', function(e) {
    e.preventDefault();
    deferredPrompt = e;
  });
})();
